spring:
  application:
    name: aec-users
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false
      mail.smtp.ssl.trust: ${MAIL_HOST}
    default-encoding: UTF-8

  # === ¡AJUSTE CLAVE AQUÍ PARA USAR LAS VARIABLES DE RAILWAY DIRECTAMENTE! ===
  datasource:
    url: ${DATABASE_URL} # Railway inyecta esta variable
    username: ${PGUSER}    # Railway inyecta esta variable
    password: ${PGPASSWORD} # Railway inyecta esta variable
    driver-class-name: org.postgresql.Driver # IMPORTANTE: Añadir o verificar esto

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update} # Considera 'none' o 'validate' para Railway
    show-sql: true # Útil para depuración
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  accessMs: ${JWT_ACCESS_MS:3600000}
  refreshMs: ${JWT_REFRESH_MS:86400000}

server:
  port: ${SERVER_PORT:8081}

admin:
  email: ${ADMIN_EMAIL}

docker:
  compose:
    enabled: false